---
kind: pipeline
type: docker
name: Rust

platform:
  arch: arm64

steps:
  - name: Test
    image: rust
    commands:
      - cargo test
    depends_on:
      - clone

  - name: Rustfmt
    image: rust
    commands:
      - rustup component add rustfmt
      - cargo fmt --check
    depends_on:
      - clone

  - name: Clippy
    image: rust
    commands:
      - rustup component add clippy
      - cargo clippy -- -D warnings
    depends_on:
      - clone

  - name: Code coverage
    image: rust
    commands:
      - cargo install cargo-tarpaulin
      - cargo tarpaulin --verbose --workspace --ignore-tests
    depends_on:
      - clone

trigger:
  event:
    - push
    - pull_request
