---
kind: pipeline
type: docker
name: Rust

platform:
  arch: arm64

steps:
  - name: Test
    image: rust
    commands:
      - cargo test

  - name: Rustfmt
    image: rust
    commands:
      - rustup component add rustfmt
      - cargo fmt --check

  - name: Clippy
    image: rust
    commands:
      - rustup component add clippy
      - cargo clippy -- -D warnings

  - name: Code coverage
    image: xd009642/tarpaulin
    commands:
      - cargo tarpaulin --verbose --workspace

trigger:
  event:
    - push
    - pull_request
